package br.com.noke.twogether.model

enum class Category {
    TECNOLOGIA, NOTICIAS, GADGETS, SAUDE, VINHOS_E_BEBIDAS, HUMOR, CULTURA,
    EMPREENDEDORISMO, FINANCAS_PESSOAIS, PROPAGANDA_E_MARKETING, ARQUITETURA,
    BELEZA, DESIGN, FOTOGRAFIA, NEGOCIOS, ESPORTES, BASQUETE, MODA, VIAGEM,
    POLITICA, GASTRONOMIA, MUSICA, CINEMA, JOGOS, AUTO, CIENCIA
}